[package]
name = "rust_graphql_parser"
version = "0.1.0"
edition = "2021"
authors = ["Filip Pacanowski <fpacanowski@gmail.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.4" }
